# Generated by Django 3.1.7 on 2021-03-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instar', '0002_auto_20210329_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Post',
        ),
    ]
