# Generated by Django 3.1.7 on 2021-03-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instar', '0004_auto_20210330_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
