# Generated by Django 3.1.7 on 2021-04-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instar', '0007_auto_20210403_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
