# Generated by Django 3.1.7 on 2021-04-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instar', '0008_remove_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
